name = "ai-cfm"
main = "worker.js"
workers_dev = true
compatibility_date = "2025-02-03"
send_metrics = false
minify = false
upload_source_maps = true

[ai]
binding = "AI"

[build]
command = ""

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
API_KEY = ""
